---

- name: Playbook 5 penggunaan global vars
  hosts: server
  vars:
    - var1: Ini esa
    - var2: Ini putri
  tasks:
    - name: var 1
      shell: echo "satu adalah {{ var1 }}, dua adalah {{ var2 }}" > /home/automate/hasil-var2.txt
    - name: var 2
      shell: echo "satu adalah {{ var2 }}, dua adalah {{ var1 }}" >> /home/automate/hasil-var2.txt
