---

- name: Playbook 3 ignore errors
  hosts: server
  tasks:
    - name: Get Linux Info
      shell: uname -a > /home/automate/info-new1.txt
      ignore_errors: yes
    - name: Get uptime
      shell: uptime >> /home/automate/info-new1.txt
