---

- name: Playbook 11 mematikan gather fact, tidak semua gather fact harus nyala terus
  hosts: server
  gather_facts: no
  tasks:
    - name: task 1
      shell: echo "ini {{ os }}" > /home/automate/os.txt

    - name: task 2
      shell: echo "ini {{ aa }}" >> /home/automate/os.txt
